/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of checklists
         * @description Get a list of expert distributions
         */
        get: operations["getChecklists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/lsids/{lsid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get checklist items by LSID */
        get: operations["getChecklistItemsByLSID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a checklist item */
        get: operations["getChecklistItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of expert distributions
         * @description Get a list of expert distributions
         */
        get: operations["getDistributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions/lsids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of species level LSIDs that have an expert distribution */
        get: operations["getLsids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/lsids/{lsid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get expert distributions by LSID
         * @description Get expert distributions by LSID
         */
        get: operations["getExpertDistributionsByLsid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/map/png/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get expert distribution image by id
         * @deprecated
         * @description Get expert distribution image by id
         */
        get: operations["getExpertDistributionImageById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an expert distribution by Id
         * @description Get an expert distribution by Id
         */
        get: operations["getExpertDistributionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fieldsdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of fields for indexing
         * @description Get a list of fields for indexing
         */
        get: operations["getFieldsForIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of fields
         * @description Get a list of fields
         */
        get: operations["getFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * search for fields
         * @deprecated
         */
        get: operations["searchFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fields/layers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** search for layers */
        get: operations["searchLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a field by Id
         * @description Get a field by Id. Includes all objects associated with the field.
         */
        get: operations["getFieldById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get intersection for many points and fields */
        post: operations["intersectBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/batch/download/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get intersection batch result */
        get: operations["intersectBatchDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/batch/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get intersection batch status */
        get: operations["intersectBatchStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/geojson/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get intersection of GeoJSON and one field
         * @deprecated
         */
        post: operations["intersectGeoJSON"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/{ids}/{lat}/{lng}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get intersection of a point and one or more fields */
        get: operations["intersectPoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/object/{fid}/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get intersection of a spatial object and one field */
        get: operations["intersectObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/pointradius/{fid}/{lat}/{lng}/{radius}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get intersection of a circle and one or more fields
         * @deprecated
         */
        get: operations["intersectCircle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/reloadconfig": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clear caches
         * @deprecated
         */
        get: operations["clearCache"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intersect/wkt/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get intersection of WKT and one field
         * @deprecated
         */
        post: operations["intersectWKT"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journalMap/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get count of Journal Map records within an area */
        get: operations["countJournalMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journalMap/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of Journal Map records within an area */
        get: operations["searchJournalMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/layers.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get CSV list of layers */
        get: operations["getLayersCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/download/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get zipped copy of the layer if permitted */
        get: operations["getLayerFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/grids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of all environmental (raster) layers
         * @deprecated
         */
        get: operations["listEnvironmentalLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/img/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get thumbnail image of layer */
        get: operations["getLayerImage_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of all layers */
        get: operations["listLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/rif-cs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of all layers in RIF-CS format
         * @deprecated
         */
        get: operations["listLayersRIFCS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** search for layers */
        get: operations["searchLayers_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/shapes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of all contextual (vector) layers
         * @deprecated
         */
        get: operations["listContextualLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a layer by layer ID */
        get: operations["getLayerById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layerDistances/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a layer association distances as CSV
         * @deprecated
         */
        get: operations["getLayerDistancesCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layerDistances/csvRawnames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a layer association distances as CSV with internal names
         * @deprecated
         */
        get: operations["getLayerDistancesRawnamesCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layerDistances/layerdistancesJSON": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a layer association distances as JSON */
        get: operations["getLayerDistancesJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an entry to the log */
        post: operations["log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the log */
        get: operations["logSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of objects in a field
         * @deprecated
         */
        get: operations["objectsInField"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/object/intersect/{pid}/{lat}/{lng}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test if a point intersects a single object */
        get: operations["nearestObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{fid}/{lat}/{lng}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of objects nearest to a point */
        get: operations["nearestObjects_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/inarea/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a list of a field's objects that intersect with provided WKT */
        post: operations["objectsInWkt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/object/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a spatial object */
        get: operations["getSpatialObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user report as CSV */
        get: operations["getUserReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task report as CSV */
        get: operations["getTaskReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a CSV or zipped CSV file containing occurrence points */
        delete: operations["deleteCSV"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of a CSV or zipped CSV file containing occurrence points */
        get: operations["statusCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a CSV or zipped CSV file containing occurrence points */
        post: operations["uploadCSV"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search all objects by name */
        get: operations["searchObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an object */
        delete: operations["deleteObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shapes/geojson/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get GeoJSON for an object */
        get: operations["getGeoJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shapes/kml/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get KML for an object */
        get: operations["getKML"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/shp/{shapeId}/featureIndex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an object from a list of features of an uploaded shapefile */
        post: operations["uploadShapefileFeature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/shp/image/{shapeId}/{featureIndexes}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return an image for an uploaded shapefile and a list of features */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shapes/shp/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get zipped shapefile for an object */
        get: operations["getShapefile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/geojson/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update an object with new GeoJSON */
        post: operations["updateGeoJSON"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/wkt/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update an object with new WKT */
        post: operations["updateWKT"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an object from GeoJSON */
        post: operations["uploadGeoJSON"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/shp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a zipped shapefile and get a shapeId */
        post: operations["uploadShapefile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shape/upload/wkt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an object from WKT */
        post: operations["uploadWkt_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shapes/wkt/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get WKT for an object */
        get: operations["getWKT"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tabulation/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List of field pairs with pre-generated tabulations */
        get: operations["listTabulations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tabulation/data/{fid1}/{fid2}/tabulation.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get details of a field pair intersection */
        get: operations["showTabulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tabulation/single/{fid}/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intersect a field with an area and return tabulated intersection information */
        get: operations["intersectTabulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/cancel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cancel a task */
        get: operations["cancel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List of tasks and their inputs and outputs */
        get: operations["capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a task with JSON body or query parameters */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/status/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task status */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of tracks
         * @description Get a list of tracks
         */
        get: operations["getTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/lsids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of species level LSIDs that have a track */
        get: operations["getLsids_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/lsids/{lsid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tracks by LSID */
        get: operations["getTracksByLsid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/track/map/png/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get image of track by id
         * @deprecated
         */
        get: operations["getTrackImageById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/track/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a track by Id */
        get: operations["getTrackById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Distributions: {
            /** Format: int64 */
            gid?: number;
            /** Format: int64 */
            spcode?: number;
            scientific?: string;
            authority_?: string;
            common_nam?: string;
            family?: string;
            genus_name?: string;
            specific_n?: string;
            /** Format: double */
            min_depth?: number;
            /** Format: double */
            max_depth?: number;
            /** Format: double */
            pelagic_fl?: number;
            estuarine_fl?: boolean;
            coastal_fl?: boolean;
            desmersal_fl?: boolean;
            metadata_u?: string;
            wmsurl?: string;
            lsid?: string;
            family_lsid?: string;
            genus_lsid?: string;
            caab_species_number?: string;
            caab_family_number?: string;
            area_name?: string;
            pid?: string;
            type?: string;
            checklist_name?: string;
            /** Format: double */
            area_km?: number;
            notes?: string;
            /** Format: int32 */
            geom_idx?: number;
            group_name?: string;
            data_resource_uid?: string;
            image_quality?: string;
            endemic?: boolean;
            genus_exemplar?: string;
            family_exemplar?: string;
            /** Format: double */
            intersectArea?: number;
            imageUrl?: string;
            /** Format: int64 */
            id?: number;
        };
        Fields: {
            id?: string;
            name?: string;
            desc?: string;
            type?: string;
            spid?: string;
            sname?: string;
            sdesc?: string;
            indb?: boolean;
            enabled?: boolean;
            /** Format: date-time */
            last_update?: string;
            namesearch?: boolean;
            defaultlayer?: boolean;
            intersect?: boolean;
            layerbranch?: boolean;
            analysis?: boolean;
            addtomap?: boolean;
            requestedId?: string;
            /** Format: int32 */
            number_of_objects?: number;
            layer?: components["schemas"]["Layers"];
            wms?: string;
            objects?: components["schemas"]["SpatialObjects"][];
            layerId?: Record<string, never>;
        };
        Layers: {
            /** Format: int64 */
            id?: number;
            uid?: string;
            name?: string;
            displayname?: string;
            description?: string;
            type?: string;
            source?: string;
            path?: string;
            displaypath?: string;
            scale?: string;
            extents?: string;
            /** Format: double */
            minlatitude?: number;
            /** Format: double */
            minlongitude?: number;
            /** Format: double */
            maxlatitude?: number;
            /** Format: double */
            maxlongitude?: number;
            notes?: string;
            enabled?: boolean;
            environmentalvaluemin?: string;
            environmentalvaluemax?: string;
            environmentalvalueunits?: string;
            lookuptablepath?: string;
            metadatapath?: string;
            classification1?: string;
            classification2?: string;
            mddatest?: string;
            citation_date?: string;
            datalang?: string;
            mdhrlv?: string;
            respparty_role?: string;
            licence_level?: string;
            licence_link?: string;
            licence_notes?: string;
            source_link?: string;
            keywords?: string;
            path_orig?: string;
            path_1km?: string;
            path_250m?: string;
            domain?: string;
            pid?: string;
            /** Format: date-time */
            dt_added?: string;
            fields?: components["schemas"]["Fields"][];
            requestedId?: string;
        };
        SpatialObjects: {
            pid?: string;
            description?: string;
            name?: string;
            fid?: string;
            /** Format: int32 */
            name_id?: number;
            bbox?: string;
            /** Format: double */
            area_km?: number;
            namesearch?: boolean;
            /** Format: double */
            degrees?: number;
            /** Format: double */
            distance?: number;
            wmsurl?: string;
            featureType?: string;
            centroid?: string;
            fieldname?: string;
            /** Format: int64 */
            id?: number;
        };
        Log: {
            /** Format: date-time */
            created?: string;
            category1?: string;
            category2?: string;
            data?: string;
            userId?: string;
            sessionId?: string;
            /** Format: int64 */
            id?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getChecklists: {
        parameters: {
            query?: {
                /** @description LSIDs to filter, comma delimited */
                lsids?: string;
                /** @description Geometry index to filter */
                geom_idx?: number;
                /** @description Data resource UIDs to filter, comma delimited */
                data_resource_uids?: string;
                /** @description WKT or Object ID to filter */
                wkt?: string;
                /** @description Object ID to filter */
                pid?: string;
                /** @description Starting index for pagination */
                start?: string;
                /** @description Page size for pagination */
                pageSize?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of checklists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getChecklistItemsByLSID: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description LSID of the checklist item */
                lsid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List checklist items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getChecklistItem: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description Id of the checklist item */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description checklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"];
                };
            };
        };
    };
    getDistributions: {
        parameters: {
            query?: {
                /** @description LSID to filter */
                lsids?: string;
                /** @description Geometry index to filter */
                geom_idx?: number;
                /** @description Data resource UIDs to filter */
                data_resource_uids?: string;
                /** @description WKT or Object ID to filter */
                wkt?: string;
                /** @description Object ID to filter */
                pid?: string;
                /** @description Starting index for pagination */
                start?: string;
                /** @description Page size for pagination */
                pageSize?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of expert distributions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getLsids: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of LSIDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getExpertDistributionsByLsid: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description LSID of the expert distribution */
                lsid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List expert distributions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getExpertDistributionImageById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LSID of the expert distribution */
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview image of the expert distribution in the Australian region */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
        };
    };
    getExpertDistributionById: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description Id of the expert distribution */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description expert distribution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"];
                };
            };
        };
    };
    getFieldsForIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields for indexing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fields"][];
                };
            };
        };
    };
    getFields: {
        parameters: {
            query?: {
                /** @description restrict to field names that contain this value and include layer information */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fields"][];
                };
            };
        };
    };
    searchFields: {
        parameters: {
            query?: {
                /** @description restrict to field names that contain this value */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fields"];
                };
            };
        };
    };
    searchLayers: {
        parameters: {
            query?: {
                /** @description restrict to layer names that contain this value */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"];
                };
            };
        };
    };
    getFieldById: {
        parameters: {
            query?: {
                /** @description starting index for associated objects */
                start?: number;
                /** @description number of associated objects to return */
                pageSize?: number;
                /** @description restrict to associated object names that contain this value */
                q?: string;
            };
            header?: never;
            path: {
                /** @description Id of the field */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description field */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fields"];
                };
            };
        };
    };
    intersectBatch: {
        parameters: {
            query: {
                /**
                 * @description Comma delimited list of field IDs
                 * @example cl22,cl23
                 */
                fids: string;
                /**
                 * @description Comma delimited list of `latitude,longitude`
                 * @example -22,134,-23,130
                 */
                points: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status of the batch request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    intersectBatchDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Batch ID
                 * @example 15123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result of the batch request as a zipped CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
    intersectBatchStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Batch ID
                 * @example 15123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status of the batch request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example null */
                    "application/json": string[];
                };
            };
        };
    };
    intersectGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description field ID
                 * @example cl22
                 */
                fid: string;
            };
            cookie?: never;
        };
        /** @description GeoJSON */
        requestBody?: {
            content: {
                "*/*": string;
            };
        };
        responses: {
            /** @description Intersection results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    intersectPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Comma delimited list of field IDs
                 * @example cl22
                 */
                ids: string;
                /**
                 * @description Latitude
                 * @example -22
                 */
                lat: number;
                /**
                 * @description Longitude
                 * @example 134
                 */
                lng: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersection results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example null */
                    "application/json": string[];
                };
            };
        };
    };
    intersectObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description field ID
                 * @example cl22
                 */
                fid: string;
                /**
                 * @description Spatial Object ID
                 * @example 123
                 */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersection results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    intersectCircle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Comma delimited list of field IDs
                 * @example cl22
                 */
                fid: string;
                /**
                 * @description Latitude
                 * @example -22
                 */
                lat: number;
                /**
                 * @description Longitude
                 * @example 134
                 */
                lng: number;
                /**
                 * @description Longitude
                 * @example 134
                 */
                radius: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersection results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    clearCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification that the reload of config was successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    intersectWKT: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description field ID
                 * @example cl22
                 */
                fid: string;
            };
            cookie?: never;
        };
        /** @description WKT */
        requestBody?: {
            content: {
                "*/*": string;
            };
        };
        responses: {
            /** @description Intersection results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    countJournalMap: {
        parameters: {
            query?: {
                /** @description WKT to filter */
                wkt?: string;
                /** @description Object ID to filter */
                pid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    searchJournalMap: {
        parameters: {
            query?: {
                /** @description WKT to filter. Required if pid is not provided. */
                wkt?: string;
                /** @description Object ID to filter. Required if wkt is not provided. */
                pid?: string;
                /** @description starting index for associated objects */
                offset?: number;
                /** @description number of associated objects to return */
                max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of JournalMap items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getLayersCSV: {
        parameters: {
            query?: {
                /** @description Set as True to include layer usage information */
                usage?: boolean;
                /** @description Number of months for the usage. Default is 12 */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/csv": unknown;
                };
            };
        };
    };
    getLayerFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description zipped layer file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
    listEnvironmentalLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"][];
                };
            };
        };
    };
    getLayerImage_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer short name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            /** @description Image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpg": unknown;
                };
            };
        };
    };
    listLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"][];
                };
            };
        };
    };
    listLayersRIFCS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/xml": components["schemas"]["Layers"][];
                };
            };
        };
    };
    searchLayers_1: {
        parameters: {
            query?: {
                /** @description restrict to layer names that contain this value */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"];
                };
            };
        };
    };
    listContextualLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"][];
                };
            };
        };
    };
    getLayerById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layers"];
                };
            };
        };
    };
    getLayerDistancesCSV: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer distances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
    getLayerDistancesRawnamesCSV: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer distances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
    getLayerDistancesJSON: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Layer distances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    log: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*": components["schemas"]["Log"];
            };
        };
        responses: {
            /** @description Valid request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logSearch: {
        parameters: {
            query?: {
                /**
                 * @description Format of response, application/csv or application/json. The default is application/json.
                 * @example application/json
                 */
                accept?: string;
                /**
                 * @description Maximum number of rows to return
                 * @example 10
                 */
                max?: string;
                /**
                 * @description Offset value for paging
                 * @example 0
                 */
                offset?: string;
                /**
                 * @description Grouping for results. A comma delimited list of: "category1", "category2", "data", "sessionId", "userId", "year", "month".
                 * @example year,category1,category2
                 */
                groupBy?: string;
                /**
                 * @description Type of counts. This is number of records or the number of unique users, sessions, etc. A comma delimited list of: "category1", "category2", "record", "session", "user"
                 * @example record,session,user
                 */
                countBy?: string;
                /**
                 * @description When true, return results for all users if request has an admin role.
                 * @example true
                 */
                admin?: string;
                /** @description Limit results to a single category1 value. */
                category1?: string;
                /** @description Limit results to a single category2 value. */
                category2?: string;
                /** @description Limit results to a single sessionId value. */
                sessionId?: string;
                /**
                 * @description Limit results between a startDate and endDate.
                 * @example 2000-01-24
                 */
                startDate?: string;
                /**
                 * @description Limit results between a startDate and endDate.
                 * @example 2025-01-24
                 */
                endDate?: string;
                /**
                 * @description Exclude users having specific roles in their profile. Used with admin=true requests
                 * @example ROLE_ADMIN, ROLE_EDITOR
                 */
                excludeRoles?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Valid request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    objectsInField: {
        parameters: {
            query?: {
                /** @description Paging start index */
                start?: number;
                /** @description Paging page size */
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Field ID */
                fid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spatial Object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    nearestObjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
                /** @description latitude */
                lat: number;
                /** @description longitude */
                lng: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spatial Object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"];
                };
            };
        };
    };
    nearestObjects_1: {
        parameters: {
            query?: {
                /** @description maximum number of items to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Field ID */
                fid: string;
                /** @description latitude */
                lat: number;
                /** @description longitude */
                lng: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spatial Object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    objectsInWkt: {
        parameters: {
            query: {
                /** @description WKT. pid or wkt is required */
                wkt?: string;
                /** @description Maximum number of objects to return */
                limit: string;
                /** @description Object ID. pid or wkt is required */
                pid?: string;
            };
            header?: never;
            path: {
                /** @description Field ID */
                fid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spatial Object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"][];
                };
            };
        };
    };
    getSpatialObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the checklist item */
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spatial Object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialObjects"];
                };
            };
        };
    };
    getUserReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Valid request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTaskReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Valid request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCSV: {
        parameters: {
            query: {
                /** @description datasetId */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete the file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    statusCSV: {
        parameters: {
            query: {
                /** @description datasetId */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status of the file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    uploadCSV: {
        parameters: {
            query: {
                /** @description datasetName */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Uploaded CSV or zipped CSV file */
        requestBody?: {
            content: {
                "application/zip": string;
            };
        };
        responses: {
            /** @description Recognised header and a dataResourceUid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    searchObjects: {
        parameters: {
            query: {
                /** @description Search term */
                q: string;
                /** @description Paging page size */
                limit?: number;
                /** @description Paging start index */
                start?: number;
                /** @description Field IDs to search, comma delimited */
                include?: string;
                /** @description Field IDs to exclude from search, comma delimited */
                exclude?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description checklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"];
                };
            };
        };
    };
    deleteObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "plain/text": components["schemas"]["Distributions"];
                };
            };
        };
    };
    getKML: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "plain/text": components["schemas"]["Distributions"];
                };
            };
        };
    };
    uploadShapefileFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shapefile ID */
                shapeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Uploaded shapefile ID */
                shapeId: string;
                /** @description Comma delimited list of feature indexes or the keyword `all` for all features */
                featureIndexes: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image of features */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
        };
    };
    getShapefile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zipped Shapefile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": components["schemas"]["Distributions"];
                };
            };
        };
    };
    updateGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    updateWKT: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    uploadGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    uploadShapefile: {
        parameters: {
            query: {
                /** @description searchable name for the area */
                name: string;
                description: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Uploaded zip file */
        requestBody?: {
            content: {
                "application/zip": string;
            };
        };
        responses: {
            /** @description Object with the shapeId and a list of all features (areas) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    uploadWkt_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Object with the area id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getWKT: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WKT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "plain/text": components["schemas"]["Distributions"];
                };
            };
        };
    };
    listTabulations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tabulations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    showTabulation: {
        parameters: {
            query?: {
                /** @description WKT to restrict the tabulated area */
                wkt?: string;
            };
            header?: never;
            path: {
                /** @description Field ID */
                fid1: string;
                /** @description Field ID */
                fid2: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersections as Tabulations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    intersectTabulation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Field ID */
                fid: string;
                /** @description Object ID */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersections as Tabulations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create: {
        parameters: {
            query: {
                /** @description Task name */
                name: string;
                /** @description task inputs as JSON */
                inputs: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getTracks: {
        parameters: {
            query?: {
                /** @description LSID to filter */
                lsids?: string;
                /** @description Geometry index to filter */
                geom_idx?: number;
                /** @description Data resource UIDs to filter */
                data_resource_uids?: string;
                /** @description WKT or Object ID to filter */
                wkt?: string;
                /** @description Object ID to filter */
                pid?: string;
                /** @description Starting index for pagination */
                start?: string;
                /** @description Page size for pagination */
                pageSize?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getLsids_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of LSIDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getTracksByLsid: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description LSID of the tracks */
                lsid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"][];
                };
            };
        };
    };
    getTrackImageById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LSID of the track */
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview image of the track in the Australian region */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
        };
    };
    getTrackById: {
        parameters: {
            query?: {
                /** @description true to exclude WKT from the response */
                nowkt?: boolean;
            };
            header?: never;
            path: {
                /** @description Id of the track */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description track */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distributions"];
                };
            };
        };
    };
}
